### ISSUE TITLE
質問ではないのですが…

### ISSUE THREAD

**Issue by papabeard73** [yukinouz/gulp-essentials#13]
noteにて有益な記事をありがとうございました。
記載いただいた順に進めていたのですが、気になる点がありましたので記載させていただきます。

<img width="634" alt="スクリーンショット 2021-09-22 21 28 35" src="https://user-images.githubusercontent.com/67470688/134344378-c196ca1a-d79a-40b0-97e5-7a775da939c5.png">

記事途中にあります、上図の赤枠内なのですが、記載は不要なのではないでしょうか。
ここでエラーが出て詰まってしまい、結局解答コードをgitからクローンしたところ、
上記の記載は無いように見受けられます。
（見落としでしたら申し訳ありません）

ご確認いただけますと幸いです。

本投稿は不適切かと思いますので、削除していただいて大丈夫です。

**Comment by yukinouz** [comment]
こちらご指摘ありがとうございます！
一部、古い記述が残っていたようですm(_ _)m
確かに、この記述があると、fibersをインストールしておかないとエラーになってしまいます。

こちら該当の箇所修正しておきます。
（書きかけの内容があるので、公開はもう少し先になりますが...）

>本投稿は不適切かと思いますので、削除していただいて大丈夫です。

いえいえ、とても助かります！

**Comment by yukinouz** [comment]
こちら訂正したのでcloseします！

**Comment by papabeard73** [comment]
ご対応いただきましてありがとうございました！

2021年9月30日(木) 9:13 yukinouz ***@***.***>:
