### ISSUE TITLE
画像圧縮方法について

### ISSUE THREAD

**Issue by shibayan-920** [yukinouz/gulp-essentials#16]
**聞きたいことの一行まとめ**
TinyPng APIに登録して圧縮する方法以外の方法は、ありませんか？？

**問題解決するために試したこと（コードもあれば追記）**
[https://www.i-ryo.com/entry/2020/11/23/165020#%E7%94%BB%E5%83%8F%E5%9C%A7%E7%B8%AE](url)
↑の方法や、webpackでの圧縮方法など試してみたのですが、エラーでした。
ずっと使用しても、無料で圧縮する方法がいいのですが、他にも方法があればアドバイスお願いします。

**Comment by yukinouz** [comment]
ご質問ありがとうございます！
Tinypng APIですと、月500枚は無料ですが、毎月500枚以上利用する、ということでしょうか？

僕が調べた限りでは今の方法がベストなので、月500枚を超える分に関しては、ImageOptim(Mac)、Antelope(win)などを使っていただくのがいいかと思います！
