### ISSUE TITLE
Wordpress開発使用時のディレクトリ

### ISSUE THREAD

**Issue by mitsunariA** [yukinouz/gulp-essentials#20]
１．wordpress開発時のディレクトリの構造がどうなっているかを知りたい。wordpress開発時のディレクトリの構造のサンプルなどがあれば参考にしたい。
２．gulpをlocalでwordpress開発使用時にPHPファイルをどこに入れるかなどがわからない。wordpress開発でgulpを使いたい。
３．
４．GitHubでgulpファイルをダウンロードして proxy: "http://localsite.local/"を自分のサイトURLに書き換えました。
wordpressテーマのフォルダの中にgulp-essentialsを入れました。
５．
６．mitsunari
７．noteを一通り読み最後の完成版をcloneし、npm installしました。

**Comment by yukinouz** [comment]
ご質問ありがとうございます！

>wordpressテーマのフォルダの中にgulp-essentialsを入れました。

`wordpressテーマのフォルダの中に`ということは、index.phpなどと同じ階層にgulpfile.jsやnode_modulesなどなどがありますね？
ディレクトリはあっていて、手順もあっていそうなのでその状態で動きそうです。

どこで引っかかっていますでしょうか？
エラーが出るのであれば、エラー文などと合わせて状況を詳細に教えていただけると助かりますm(_ _)m

**Comment by mitsunariA** [comment]
wordpressテーマのフォルダの中にgulp-essentialsフォルダとテーマ認識の為のindex.php、style.cssが同じ階層に入っています。
phpファイルやimg,jsはgulp-essentialsのsrcフォルダに入れています。
gulpの方にエラーは出ていないのですが開いた画面は真っ白でURLはhttp://localhost:8080/と表示されています。

**Comment by yukinouz** [comment]
>gulp-essentialsフォルダと

gulp-esseintialsのフォルダの`中身`が同階層にありますかね？フォルダごとテーマフォルダ内に置くのならばパスを合わせないといけません。

もし、パスがあっていて真っ白になるようでしたら、index.php(home.php, front-page.phpがあるならそちら）に何も書いていないか、Localなどのローカルサーバーを起動しているか、などgulp以外の環境の要因もご確認くださいm(_ _)m

**Comment by yukinouz** [comment]
>phpファイルやimg,jsはgulp-essentialsのsrcフォルダに入れています。

phpファイルはsrcではなく、index.phpと同階層においてください。
（WPのディレクトリルールをもう一度ご確認いただいた方がいいかもしれません）
