### ISSUE TITLE
コードの構成がわかりません

### ISSUE THREAD

**Issue by yukaorange** [yukinouz/gulp-essentials#21]
const sass = require('gulp-sass')(require('sass'));

ここの書き方が
require(引数)(引数)
となっていますが、これがどういう処理なのか調べても分かりませんので、処理の流れを教えていただきたく思います。

**Comment by yukinouz** [comment]
すみません！
こちらの[質問ルール](https://github.com/yukinouz/gulp-essentials/issues/4)をご確認の上、再度ご質問をお願いします。
（該当しない質問項目は空白でかまいません。）

よろしくお願いいたしますm(_ _)m

**Comment by yukaorange** [comment]
1.
const sass = require('gulp-sass')(require('sass'));
がどういった処理をしているのか教えてください

2.
問題というほどではありませんが、
処理の結果が、gulp-sass('sass')が返されて変数sassに代入されているという理解で正しいのか、確認できる記事や教材がありませんでしたので、質問させていただきました。

3.
const sass = require('gulp-sass')(require('sass'));

4.
require('gulp-dart-sass')などのコードは試しました。

5.
上述2.のとおりの結論で止まっています。

6.
brainにて購入しました。yukaorangeがアカウント名です。

7.
一応、記事を参考にコンパイル、マップファイルの生成、ファイル更新を検知してブラウザリロードなどは実装済みです。

ぼんやりした質問で申し訳ありませんが、require()の理解が足りていないところ、現状の理解で進めていいのかご教示いただきたく質問いたしました。また、質問方法について失念しましたことこの場をお借りして謝罪いたします。

**Comment by yukinouz** [comment]
こちら、ご質問ありがとうございますm(_ _)m

基本的には、**gulp-sass公式の通りに書いている**というのが回答です。
https://www.npmjs.com/package/gulp-sass

上記リンクの説明を読めば大体理解できると思いますが、更に丁寧に説明します。
[Migration Guide](https://www.npmjs.com/package/gulp-sass#migrating-to-version-5)を見てみましょう。

```
Setting a Sass compiler
As of version 5, gulp-sass does not include a default Sass compiler, so you must install one (either node-sass or sass) along with gulp-sass.
```
gulp-sassバージョン5には、デフォルトのsassコンパイラーが入っていません。なので、gulp-sassと(node-sass または sass)をインストールしてください。と書いてあります。

gulp-sassはnode-sassとdart sassの両方に対応してますが、node-sassは非推奨となるのでdart sassを使います。

なので、`require('gulp-sass')(require('sass'));`で、dart sassを使って、gulp-sassを動かしますよー、という記述になっています。
