### ISSUE TITLE
お世話になっております

### ISSUE THREAD

**Issue by ShigeakiSaito** [yukinouz/gulp-essentials#24]
1. _default.pugを作成しextendsで下層ページにうまく出力されない
2.<img width="1440" alt="スクリーンショット 2022-04-20 11 16 10" src="https://user-images.githubusercontent.com/92005743/164135471-87d79a8f-994c-4767-ba54-3b754d32ac3b.png">
3.
[gulpfile.js.zip](https://github.com/yukinouz/gulp-essentials/files/8517816/gulpfile.js.zip)
[package.json.zip](https://github.com/yukinouz/gulp-essentials/files/8517822/package.json.zip)
[package-lock.json.zip](https://git
[webpack.config.js.zip](https://github.com/yukinouz/gulp-essentials/files/8517831/webpack.config.js.zip)
hub.com/yukinouz/gulp-essentials/files/8517827/package-lock.json.zip)
[src.zip](https://github.com/yukinouz/gulp-essentials/files/8517836/src.zip)
4. コンソールエラーでbecause its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.と出ているので検索にかけsrc/pug/head/_stylesheetのlinkにtype="text/cssを追記しました。htmlは出力されたのですがcssは当たっていない状況で色々調べてやっていくうちにhtmlも表示されなくなってしまいました。
5. フォルダやファイルが増えてしまいパスがあっていないのだと思います。
6. 福郎
7. noteは全て完走しました。初めてgithubなのて至らない点がありますがお手隙の際アドバイス頂けたら幸いです。一応Twitterのアカウントも載せておきます。よろしくお願いいたします。https://twitter.com/shige_co_jp

**Comment by yukinouz** [comment]
@ShigeakiSaito 

pugの運用に関することはnoteの範囲外となりますが、スクショからわかることをご回答しますね。
（[こちらの記事](https://flex-box.net/pug-customize/)のご質問と推察します。）

`http://localhost:8081/undefinedstyle.css`になっていて、ファイルパスが合っていないようです。
`undefined`となっているので、（記事の通り進めているなら）`cssPath`が定義されていないとかが理由だと思います。直接パスを書くか、`cssPath`がきちんと定義されているかやconfigファイルをincludeしているかご確認くださいm(_ _)m

**Comment by ShigeakiSaito** [comment]
のせっちさん、範囲外にも関わらず回答して下さりありがとうございましたm(_ _)m

18時間くらいやっていましたが全く分からず力を借りてしまいました泣
gulpに関してはのせっちさんのブログを参考にさせて頂いてます！本当にありがとうございましたm(_ _)m
