### ISSUE TITLE
質問：既存サイトの修正案件でのgulp導入方法について

### ISSUE THREAD

**Issue by kazu-fl** [yukinouz/gulp-essentials#25]
お世話になります。質問させていただきたく思います。
お忙しいところ恐縮ですが、ご回答頂けますと幸いです。

聞きたいことの一行まとめ
既存のhtmlサイトやワードプレスサイトの修正案件で一式データを渡された時はどのようにgulpを導入すれば良いのでしょうか？

起きている問題（起きている現象の詳細/エラーメッセージ/スクリーンショット）
index.html以外のhtmlファイルのcssの語尾に「?ver」をつけて「npx gulp cahce」をしてもdistフォルダにはindex.htmlのみが出力され、他のhtmlファイルは出力されなかった。
さらに出力されたソースコードもpugのテンプレート状態で来た（下記にソースコード）

ソースコード（関連するソースコード/全ソースコード）
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/style.css?ver=f4fa50ebeeae57ee=4e0a88ad5303ad5a=5a3900ddd0eab4dd">
    <title>Document</title>
  </head>
  <body>
    <h1 class="hoge">Hello from pug!</h1>
    <button id="js-alert-button">ボタン</button>
    <div>
      <picture class="hogeclass">
        <source media="(min-width: 768px)" srcset="./img/img-cat.webp?ver=f4fa50ebeeae57ee?ver=4e0a88ad5303ad5a?ver=5a3900ddd0eab4dd" type="image/webp"/>
        <source media="(min-width: 768px)" srcset="./img/img-cat.jpg?ver=f4fa50ebeeae57ee?ver=4e0a88ad5303ad5a?ver=5a3900ddd0eab4dd" type="image/jpg"/>
        <source media="(max-width: 767px)" srcset="./img/img-cat-smp.webp?ver=f4fa50ebeeae57ee?ver=4e0a88ad5303ad5a?ver=5a3900ddd0eab4dd" type="image/webp"/><img src="./img/img-cat-smp.jpg?ver=f4fa50ebeeae57ee?ver=4e0a88ad5303ad5a?ver=5a3900ddd0eab4dd" type="image/jpg" alt="画像の説明"/>
      </picture>
    </div>
    <script src="./js/bundle.js?ver=f4fa50ebeeae57ee=4e0a88ad5303ad5a=5a3900ddd0eab4dd"></script>
  </body>
</html>

問題解決するために試したこと（コードもあれば追記）
$ npm install
index.html以外のhtmlファイルにもスタイルシートのhrefに「?ver」をつけた
その後
$ npx gulp cache
を行った。

キャッシュリロード自体は機能しているみたい。
（vscodeのlive sereverプラグインからブラウザを起動しているのでその機能の可能性もあり。）

問題について自分なりに考えたこと（デバッグ結果/検索結果/自分なりの原因予想）
「既存サイト　gulp 導入」
「修正案件　gulp」
などで調べても、gulpが元々導入されているサイトの対処法しかでてこなかった

サイトデータのフォルダを丸々一式出力できれば既存案件でも一気にgulpを使えるのではないかと思った。
ディレクトリ例）
-元サイトフォルダ
--index.html
--cssフォルダ
--imageフォルダ
--gulpファイル色々

-gulp出力されたサイトフォルダ(マニュアル内でdistフォルダ)
--gulp出力されたindex.html
--gulp出力されたcssフォルダ
--gulp出力されたimageフォルダ

当コンテンツを購入したnoteのアカウント
brainID:
kazu-brain

noteのどのあたりまでやったのか（章のタイトル、小見出しのタイトルなど）
一通り目を通して完成ファイルをダウンロード後、gulpの実行コマンドを試し、githubにpushしてgitihub上で管理するようにした。
pugについてはかなり理解が浅いです。

以上です。
既存案件で使いたい理由としては、既存サイト全体の修正が必要だった場合、各ページごとに修正しなければいけないものをまとめてgulpで処理できるので、とても効率的になると考えたからです。
検討違いのことを行っていたら申し訳ありません。

のせっちさんが実際に既存サイトの修正の案件を受けた時のgulp使用例などご教授頂けますと幸いです。

何卒宜しくお願いします。

**Comment by yukinouz** [comment]
kazu-flさん

ご購入いただきありがとうございます。
ご質問の内容は、実案件に関する質問になり、記事の内容に関する質問ではないのかなと思います。

なので本来サポート外かと思いますが、文章からわかる範囲でご回答しますね。

## 質問内容から解決に至れそうなヒント
- ディレクリが僕の記事とは違うようなので、受領した元サイトのディレクトリ構成に合わせて、gulpfileを書き直す必要がありそう。
  - もしくは、記事で解説したのと同じディレクトリ構成に元サイト変更するか
-  元サイトがhtmlを使っているのならば、pugは使わないようにするか、元サイトのhtmlをpug化するかを検討しましょう。
   -  `出力されたソースコードもpugのテンプレート状態で来た`とありますが、これは記事で用意されているサンプルのpugファイルがコンパイルされただけです。

## まとめ
- 案件に合わせてディレクトリ構成を揃えたり、gulpfileを編集したりと微調整が必要です。

おそらく完成版をDLしたけど、記事で解説した中身までは理解できてないのではないでしょうか？
どれが、何をしているのか？どのファイルを`src`として、コンパイル後はどこに入るのか`dist`等の理解だけでもしておくと、解決に至れるかもしれません。

繰り返しになりますが、個別案件まではサポートできないですが、記事の内容を確認して動きを理解すれば解決できるのではないかと思います！

**Comment by kazu-fl** [comment]
迅速なご対応ありがとうございます。
サポート外の質問にも関わらずご回答くださりありがとうございます。

*案件のディレクトリ構成を理解すれば柔軟に使いまわしが可能
*修正案件では慣れないうちはpugを使わない方が良い
*yukinouzさんは修正案件ではgulpを使わない

という認識であっていますでしょうか？
お忙しいところ恐縮ですが何卒よろしくお願いいたします。

**Comment by yukinouz** [comment]
kazu-flさん

> *案件のディレクトリ構成を理解すれば柔軟に使いまわしが可能

そうですね！

> *修正案件では慣れないうちはpugを使わない方が良い

そうは言っていません。
`pugは使わないようにするか、元サイトのhtmlをpug化するかを検討しましょう。`と回答しました。

> *yukinouzさんは修正案件ではgulpを使わない

とても軽微な修正の場合は使わないことはあると思いますが、基本的には使います。（使わないとはどこにも書いてませんよ)

**Comment by kazu-fl** [comment]
返信ありがとうございます！

質問が分かりづらいにも関わらずご丁寧な対応ありがとうございます！

修正案件にも使えるということがわかり安心しました！
後は自分で試行錯誤して秘伝のタレを使いまわしていこうと思います！

また何かWEB制作に便利なツールなど紹介いただけましたら購入検討いたしますので、今後ともよろしくお願いいたします。
ありがとうございました！
