### ISSUE TITLE
2-4. Sassをもっと使いやすくする　ソースマップ作成の項目でコンパイルされない

### ISSUE THREAD

**Issue by okuzaki0217** [yukinouz/gulp-essentials#26]
聞きたいことの一行まとめ
ソースマップをコンパイルして作成したい。

起きている問題（起きている現象の詳細/エラーメッセージ/スクリーンショット）

`gulp-notify: [Error running Gulp] Error: Unknown browser query `last 1 versionIE 11`. Maybe you are using old Browserslist or made typo in query.`

ソースコード（関連するソースコード/全ソースコード）
```
[23:10:17] Using gulpfile ~/Desktop/gulp-essentials/gulpfile.js
[23:10:17] Starting 'sass'...
[23:10:17] Finished 'sass' after 25 ms
[23:10:17] gulp-notify: [Error running Gulp] Error: Unknown browser query `last 1 versionIE 11`. Maybe you are using old Browserslist or made typo in query.
```

問題解決するために試したこと（コードもあれば追記）
```
再度記述ミスなどないか確認し、戻り確認&コピペ。
前章でのコンパイルはされた。ソースマップ作成章でのコンパイルはされず、、、なぜ。。
```

問題について自分なりに考えたこと（デバッグ結果/検索結果/自分なりの原因予想）
エラーググりしましたが、同じような問題は出てこず。。。

当コンテンツを購入したnoteのアカウント
もさく

noteのどのあたりまでやったのか（章のタイトル、小見出しのタイトルなど）
`2-4. Sassをもっと使いやすくする`

**Comment by mosak0217** [comment]
```
次に、ルートディレクトリに『.browserslistrc』というファイルを作って下記を記述します。（最初のドット(.)必要です！）

last 1 versionIE 11
Android >= 6
```

上記のファイルの中の記述を削除して再度コンパイルしたらいけました、IEのサポートが終了しているからということですかね。

ということは、.browserslistrcファイルは不要でしょうか？

sassのコンパイルは今までは、Live Sass Compilerを使用していました。

**Comment by okuzaki0217** [comment]
諸々進んでいくうちに理解できました！ありがとう御座いました！

**Comment by yukinouz** [comment]
自己解決したようなのでクローズします。
