### ISSUE TITLE
WordPress開発での使用はできますでしょうか？

### ISSUE THREAD

**Issue by ghost** [yukinouz/gulp-essentials#27]
1. 聞きたいこと一行まとめ
ローカル環境（Local by Flywheel）でのWordPress開発をしようとしています。
gulpファイルをどのように修正すれば使用することができますでしょうか？
wp-content/themesの直下にフォルダを配置すると思いますが、gulpの中身をどのようなディレクトリ構成すれば良いか分かりかねています。

2. 起きている問題（起きている現象の詳細/エラーメッセージ/スクリーンショット）
WordPressでの開発環境構築

3.ソースコード（関連するソースコード/全ソースコード）
なし

4.問題を解決するために試したこと（コードもあり追記）
ググって解決を試みましたが、できなかったです。

5.問題について自分なりに考えたこと（アップロード結果/検索結果/自分なりの原因予想）
distフォルダの階層を変更すれば解決？

6.当コンテンツを購入したnoteのアカウント
<img width="1028" alt="スクリーンショット 2022-09-22 6 30 22" src="https://user-images.githubusercontent.com/114112200/191614090-f76e8265-72b7-4570-bb12-daa40c300069.png">

アカウント名：shouji

7.noteのどの辺りまでやったのか（章のタイトル、小見出しのタイトルなど）
一通りすべてこなしました。

以上、サポート範囲外での質問かもしれませんが
可能であればアドバイスいただけますと幸いです。
よろしくお願いいたします。

**Comment by yukinouz** [comment]
[aguu-webseisaku](https://github.com/aguu-webseisaku) さん

ご質問ありがとうございます。
WPで使用したいが、ディレクトリ構成をどうすればいいかわからない、という質問ですね。

## 質問回答の前に

本来書く必要ないですが、質問精度が上がると今後いいので書いています。

- `どういう問題が起きているか？`が書かれていません。
これでは、どこでどう詰まって質問してきているのか？が見えてきません。
（例：自分でやってみて、gulpを動かしたらどういうエラーが出た？）

- `問題を解決するために試したこと` には「ググったけどわからなかった」としてか書かれていません。
問題解決のために自分でどう仮説を立てて、何を試したというところが重要になります。
「ここまではわかるけど、ここからがわからない」、「こういう仮説を立てたけど、どうも違うっぽい」など、調べている内に質問の解像度が上がっていくはずです。質問するために調べていたら解決した、ということもザラにあります。

- `問題について自分なりに考えたこと`で`distフォルダの階層を変更すれば解決？`と書いていますが、これは試したのでしょうか？試したら解決したり、見えてくるものがあったかもしれませんよね。

質問をするな、とか、回答者のことを考えて、とか言うつもりはなく、`自分が欲しい回答をもらうために`上記のことを意識して質問するようにしてください。

## 以下回答です。

情報が少ないため、質問の中から多分こういう問題だろうな、という予想で回答することになりますのでご了承ください。

>wp-content/themesの直下にフォルダを配置すると思いますが

`wp-content/themes/テーマ`の直下です。index.phpやfunctions.phpなどと同じ階層になります。

>gulpの中身をどのようなディレクトリ構成すれば良いか

最後まで完走されたということなので、基本的にはそのまま使えます。
注意点としては、
- WPの場合はpugは使用しない。
- css,jsを読み込む際のファイルパスに気を付ける
- browsersyncの設定をWP用に変更（3章で解説しています）

以上となります。
がんばってください！

**Comment by ghost** [comment]
ご返信ありがとうございます。

お忙しい中、ご丁寧にご指摘いただきまして、ありがとうございます。
そして、わかりづらい質問の仕方をしてしまい申し訳ありませんでした。
自分自身、まだまだ意識が足らないと気づくことができたので、勉強になります。ありがとうございます。

ご回答いただいた事項を踏まえ、解決できるようやってみます。
ありがとうございます。

2022年9月22日(木) 9:23 yukinouz ***@***.***>:
