### ISSUE TITLE
回答付きだから安心と書かれていましたが全く分かりませんでした。

### ISSUE THREAD

**Issue by asdm-git** [yukinouz/gulp-essentials#28]
③完成品をDLしてサクサク使う → ドーピングコースがあるということで
git clone https://github.com/yukinouz/gulp-essentials.git
をした後にすぐ使えると思いsassをコンパイルして使いたいのですが何をしたらいいか分かりません
上をした後にnpx gulp sass　とターミナルに打ちましたがコンパイル出来ませんでしたターミナルには何を打てばコンパイルできるのですか？

10時間以上調べましたがお手上げです。ノートでは明らかに説明不足なので教えてください。

**Comment by yukinouz** [comment]
asdi-gitさん

お世話になります。
[質問ルール](https://github.com/yukinouz/gulp-essentials/issues/4)をご確認の上、再度質問していただけますでしょうか？
「できませんでした」、「わかりませんでした」では回答のしようがないためです。
お手数ですが、よろしくお願いします。

ご質問の中から答えられそうなことが一つありますので、そちらにご回答したいと思います。

>npx gulp sass　とターミナルに打ちましたがコンパイル出来ませんでした

以下が考えられますのでご確認ください。
- nodeがインストールされているか？
- `cd`コマンド等でgulp-essentialsに移動しているか？
- `gulp-essentials`のディレクトリで`npm install`を実行しているか？

上記内容は、第一章、第二章までの内容を読んでいただけると補足になると思います。

繰り返しになりますが、[質問ルール](https://github.com/yukinouz/gulp-essentials/issues/4)に沿ってご質問いただけるとより具体的な回答が可能かと思います。

よろしくお願いいたします。

**Comment by asdm-git** [comment]
聞きたいことの一行まとめ
何をすれば使えるようになるか明確に明記してほしいnoteの説明がわかりにくすぎる完成版をターミナルに打ち込んだ後の道順の説明がないのでどうしようもない

起きている問題（起きている現象の詳細/エラーメッセージ/スクリーンショット）
上で書いた通りsassが使えないどこで説明が分岐しているか全くわからない

ソースコード（関連するソースコード/全ソースコード）
ソースコード以前の問題

問題解決するために試したこと（コードもあれば追記）
nodeがインストールされているか？
cdコマンド等でgulp-essentialsに移動しているか？
gulp-essentialsのディレクトリでnpm installを実行しているか？
全てやっています。


問題について自分なりに考えたこと（デバッグ結果/検索結果/自分なりの原因予想）


当コンテンツを購入したnoteのアカウント
super_hawk652

noteのどのあたりまでやったのか（章のタイトル、小見出しのタイトルなど）
全て読んだ上で作業を短縮するために完成版のgit clone https://github.com/yukinouz/gulp-essentials.gitをvsコードのターミナルに記入した

**Comment by asdm-git** [comment]
nodeインストール後
node -v
## v14.16.1のように出てくればOK
出ました

## デスクトップに作成した場合
cd Desktop
## gulp-essentialsへ移動
cd gulp-essentials
vscodeなのでドラックアンドドロップで解決

## package.jsonを作成する
npm init -y

## Gulpをインストールする
npm i -D gulp
gulpがインストールされました

ここで完成版
git clone https://github.com/yukinouz/gulp-essentials.git
を打ちました
npm install

で？？この先noteでは解説がどこで分岐しているのですか？？？このまま進めると完成版をインストールしているのに内容が重複しますよねどういう道順で辿ればいいんですか？？？？

**Comment by yukinouz** [comment]
asdm-gitさん

ありがとうございます。
[こちらのコメント](https://github.com/yukinouz/gulp-essentials/issues/28#issuecomment-1274248562)の手順を見ますと、
1. `gulp-essentials`へ移動
1. `npm init -y`
1. Gulpのインストール
1.  `git clone https://github.com/yukinouz/gulp-essentials.git`
1. `npm install`

と進めたのでしょうか？そうすると、gulp-essentialsの中に更に

**Comment by yukinouz** [comment]
asdm-gitさん

ありがとうございます。
[こちらのコメント](https://github.com/yukinouz/gulp-essentials/issues/28#issuecomment-1274248562)の手順を見ますと、
1. `cd Desktop`
1. `gulp-essentials`へ移動
1. package.jsonを作成(`npm init -y`)
1. Gulpのインストール(`npm i -D gulp`)
1.  `git clone https://github.com/yukinouz/gulp-essentials.git`
1. `npm install`

と進めたのでしょうか？そうすると、gulp-essentialsの中に更にgulp-essentialsができているのではないでしょうか...？

以下の手順ではどうでしょうか？

 （デスクトップに既に`gulp-essentials`という名前のフォルダが存在しているなら先に削除しておく）（追記）
1. `cd Desktop`
2. `git clone https://github.com/yukinouz/gulp-essentials.git`
3. `cd gulp-essentials`
4. `npm install`
5. `npx gulp sass`

>この先noteでは解説がどこで分岐しているのですか？？？

分岐はしません。完成まで一本道となります。

>完成版をインストールしているのに内容が重複しますよねどういう道順で辿ればいいんですか？？？

完成版はnoteで解説した内容を全て含みます。

**Comment by asdm-git** [comment]
（デスクトップに既にgulp-essentialsという名前のフォルダが存在しているなら先に削除しておく）（追記）

cd Desktop
git clone https://github.com/yukinouz/gulp-essentials.git
cd gulp-essentials
npm install
npx gulp sass
この順番でやってみたらエラーが出ました
<img width="1440" alt="スクリーンショット 2022-10-11 22 18 57" src="https://user-images.githubusercontent.com/115526895/195102044-090e0bd2-4f12-4de3-a59c-eb4192810557.png">
<img width="1440" alt="スクリーンショット 2022-10-11 22 18 49" src="https://user-images.githubusercontent.com/115526895/195102068-2be4af17-6ef4-4e85-ae04-2baecac2e27d.png">
<img width="1440" alt="スクリーンショット 2022-10-11 22 18 37" src="https://user-images.githubusercontent.com/115526895/195102077-bfaa5f98-5d2d-4898-b251-c6738ca83440.png">
<img width="1440" alt="スクリーンショット 2022-10-11 22 18 14" src="https://user-images.githubusercontent.com/115526895/195102082-0baf5aba-76de-4e85-bcd5-35cd5aaf8812.png">

**Comment by yukinouz** [comment]
ありがとうございます。
`npm install` のところでエラーが出ているようです。

本日外出のため回答遅くなりそうですが、僕の環境でエラー再現できるか確認してご回答します。ご不便をおかけし申し訳ありません。

念の為確認なのですが、お使いのnodeバージョンを教えていただけますか？
`node -v` で確認できます。

よろしくお願いします。

**Comment by yukinouz** [comment]
asdm-gitさん

こちら、下記を試してみていただけますでしょうか？

(gulp-essentialsに移動後）
1. `npm rm -D node-sass`
2. `npm install`
3. `npx gulp sass`

よろしくお願いします。

**Comment by asdm-git** [comment]
cd Desktop
git clone https://github.com/yukinouz/gulp-essentials.git
cd gulp-essentials
npm install
npx gulp sass
これをもう1度デスクトップの配流を消してやってみました

**Comment by asdm-git** [comment]
node -v
<img width="1440" alt="スクリーンショット 2022-10-13 11 32 53" src="https://user-images.githubusercontent.com/115526895/195485611-bc2cb5e0-482d-4ec8-9362-4760cfb6fca1.png">

**Comment by asdm-git** [comment]
npm rm -D node-sass
npm install
npx gulp sass
<img width="1440" alt="スクリーンショット 2022-10-13 11 35 14" src="https://user-images.githubusercontent.com/115526895/195485773-60214605-0764-44b6-aedf-e42acfdf9715.png">

**Comment by asdm-git** [comment]
という感じです。よろしくお願いします。

**Comment by yukinouz** [comment]
asdm-gitさん

ありがとうございます。
https://github.com/yukinouz/gulp-essentials/issues/28#issuecomment-1276950444
こちらでsassのコンパイル通ってますね。使える状態になっています。

**Comment by asdm-git** [comment]
<img width="1440" alt="スクリーンショット 2022-10-13 14 11 57" src="https://user-images.githubusercontent.com/115526895/195507295-b93b9d3f-1da5-4cc7-811b-f7dd2f95d630.png">
cssファイルを開くと8件エラー表示が出ます（特に何も触っていない状態で）

**Comment by asdm-git** [comment]
またコンパイルされているか試すためにscssの$red: #f00;  →  $red: #fff;に変えてみましたがcssファイルに何ら変わりがありませんでした。
<img width="1440" alt="スクリーンショット 2022-10-13 14 15 10" src="https://user-images.githubusercontent.com/115526895/195507683-a830d394-396f-4ba6-b038-a03d4115b739.png">
<img width="1440" alt="スクリーンショット 2022-10-13 14 14 57" src="https://user-images.githubusercontent.com/115526895/195507688-addfae8d-9ad7-475b-b1b3-6b68c6688aab.png">
#red

**Comment by yukinouz** [comment]
asdm-gitさん

>cssファイルを開くと8件エラー表示が出ます（特に何も触っていない状態で）

こちらはお使いのLintツールやスペルチェッカー等の問題かと思いますので、僕の方では対応できかねます。

>またコンパイルされているか試すためにscssの$red: #f00; → $red: #fff;に変えてみましたがcssファイルに何ら変わりがありませんでした。

こちらのスクショ2枚からは、style.scssの`$red: #f00;`を`$red: #fff;`に変更した、というところまでしか読み取れないのですが、style.scssを変更後、`npx gulp sass`は実行されましたでしょうか？

**Comment by asdm-git** [comment]
こちらはお使いのLintツールやスペルチェッカー等の問題かと思いますので、僕の方では対応できかねます。
これについては理解しました。

style.scssを変更した後、は実行npx gulp sasするとコンパイルできたのですが、vscodeのライブscssコンパイラーのように自動でリアルタイムにコンパイルされると思っていたのですが変更するたびにいちいちnpx gulp sassを実行しないといけないものなのですか？

**Comment by yukinouz** [comment]
asdm-git

>vscodeのライブscssコンパイラーのように自動でリアルタイムにコンパイルされると思っていたのですが変更するたびにいちいちnpx gulp sassを実行しないといけないものなのですか？

その場合は、`npx gulp`または`npm run dev`を使用してください。
noteに記載している内容になるので、再度ご確認ください。

**Comment by asdm-git** [comment]
<img width="1440" alt="スクリーンショット 2022-11-11 15 35 04" src="https://user-images.githubusercontent.com/115526895/201278457-94d7776b-1c46-4b08-ac58-f079a95d84b8.png">
<img width="1440" alt="スクリーンショット 2022-11-11 15 34 57" src="https://user-images.githubusercontent.com/115526895/201278462-95b28c82-0d4e-4c27-a99c-d082c2f93697.png">
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],は何が原因でエラーが出ているのですか？

**Comment by asdm-git** [comment]
The following tasks did not complete: build, tinyPng
[15:34:08] Did you forget to signal async completion?
またtinyPngでもエラーが出ているようです。

**Comment by yukinouz** [comment]
こちらご質問ありがとうございます。

>digital envelope routines unsupported

こちらのエラー文を調べてみると、nodeのバージョンが高すぎるようです。
僕のnoteについては、node `v14.16.1`で動作保証しているので、そちらのバージョンで再度お試しいただけますでしょうか？

よろしくお願いします。

**Comment by asdm-git** [comment]
![Uploading スクリーンショット 2022-11-13 10.38.17.png…]()

**Comment by asdm-git** [comment]
<img width="1440" alt="スクリーンショット 2022-11-13 10 38 17" src="https://user-images.githubusercontent.com/115526895/201501429-89f3cfee-2e20-4d5f-9fc3-dd8735f089b1.png">
<img width="1440" alt="スクリーンショット 2022-11-13 10 38 13" src="https://user-images.githubusercontent.com/115526895/201501431-e5b1c53c-ea76-4f5b-8017-431f846861f0.png">
<img width="1440" alt="スクリーンショット 2022-11-13 10 38 08" src="https://user-images.githubusercontent.com/115526895/201501432-5db78a52-40ca-4f6d-a81e-881fa5419c6c.png">
<img width="1440" alt="スクリーンショット 2022-11-13 10 38 00" src="https://user-images.githubusercontent.com/115526895/201501433-916b2cb7-fff8-4f84-9444-b41049c7093f.png">

**Comment by asdm-git** [comment]
M1 Mac だどとこのようになりほかの方法もいくつか試しましたが一向に前に進めません

**Comment by asdm-git** [comment]
moritahayato@moritasatsuhitonoMacBook-Air Ishii-kadan % nodebrew ls
v18.10.0

current: v18.10.0
moritahayato@moritasatsuhitonoMacBook-Air Ishii-kadan % nodebrew list
v18.10.0

current: v18.10.0
moritahayato@moritasatsuhitonoMacBook-Air Ishii-kadan % nodebrew ls-remote
v0.0.1    v0.0.2    v0.0.3    v0.0.4    v0.0.5    v0.0.6    

v0.1.0    v0.1.1    v0.1.2    v0.1.3    v0.1.4    v0.1.5    v0.1.6    v0.1.7
v0.1.8    v0.1.9    v0.1.10   v0.1.11   v0.1.12   v0.1.13   v0.1.14   v0.1.15
v0.1.16   v0.1.17   v0.1.18   v0.1.19   v0.1.20   v0.1.21   v0.1.22   v0.1.23
v0.1.24   v0.1.25   v0.1.26   v0.1.27   v0.1.28   v0.1.29   v0.1.30   v0.1.31
v0.1.32   v0.1.33   v0.1.90   v0.1.91   v0.1.92   v0.1.93   v0.1.94   v0.1.95
v0.1.96   v0.1.97   v0.1.98   v0.1.99   v0.1.100  v0.1.101  v0.1.102  v0.1.103
v0.1.104  

v0.2.0    v0.2.1    v0.2.2    v0.2.3    v0.2.4    v0.2.5    v0.2.6    

v0.3.0    v0.3.1    v0.3.2    v0.3.3    v0.3.4    v0.3.5    v0.3.6    v0.3.7
v0.3.8    

v0.4.0    v0.4.1    v0.4.2    v0.4.3    v0.4.4    v0.4.5    v0.4.6    v0.4.7
v0.4.8    v0.4.9    v0.4.10   v0.4.11   v0.4.12   

v0.5.0    v0.5.1    v0.5.2    v0.5.3    v0.5.4    v0.5.5    v0.5.6    v0.5.7
v0.5.8    v0.5.9    v0.5.10   

v0.6.0    v0.6.1    v0.6.2    v0.6.3    v0.6.4    v0.6.5    v0.6.6    v0.6.7
v0.6.8    v0.6.9    v0.6.10   v0.6.11   v0.6.12   v0.6.13   v0.6.14   v0.6.15
v0.6.16   v0.6.17   v0.6.18   v0.6.19   v0.6.20   v0.6.21   

v0.7.0    v0.7.1    v0.7.2    v0.7.3    v0.7.4    v0.7.5    v0.7.6    v0.7.7
v0.7.8    v0.7.9    v0.7.10   v0.7.11   v0.7.12   

v0.8.0    v0.8.1    v0.8.2    v0.8.3    v0.8.4    v0.8.5    v0.8.6    v0.8.7
v0.8.8    v0.8.9    v0.8.10   v0.8.11   v0.8.12   v0.8.13   v0.8.14   v0.8.15
v0.8.16   v0.8.17   v0.8.18   v0.8.19   v0.8.20   v0.8.21   v0.8.22   v0.8.23
v0.8.24   v0.8.25   v0.8.26   v0.8.27   v0.8.28   

v0.9.0    v0.9.1    v0.9.2    v0.9.3    v0.9.4    v0.9.5    v0.9.6    v0.9.7
v0.9.8    v0.9.9    v0.9.10   v0.9.11   v0.9.12   

v0.10.0   v0.10.1   v0.10.2   v0.10.3   v0.10.4   v0.10.5   v0.10.6   v0.10.7
v0.10.8   v0.10.9   v0.10.10  v0.10.11  v0.10.12  v0.10.13  v0.10.14  v0.10.15
v0.10.16  v0.10.17  v0.10.18  v0.10.19  v0.10.20  v0.10.21  v0.10.22  v0.10.23
v0.10.24  v0.10.25  v0.10.26  v0.10.27  v0.10.28  v0.10.29  v0.10.30  v0.10.31
v0.10.32  v0.10.33  v0.10.34  v0.10.35  v0.10.36  v0.10.37  v0.10.38  v0.10.39
v0.10.40  v0.10.41  v0.10.42  v0.10.43  v0.10.44  v0.10.45  v0.10.46  v0.10.47
v0.10.48  

v0.11.0   v0.11.1   v0.11.2   v0.11.3   v0.11.4   v0.11.5   v0.11.6   v0.11.7
v0.11.8   v0.11.9   v0.11.10  v0.11.11  v0.11.12  v0.11.13  v0.11.14  v0.11.15
v0.11.16  

v0.12.0   v0.12.1   v0.12.2   v0.12.3   v0.12.4   v0.12.5   v0.12.6   v0.12.7
v0.12.8   v0.12.9   v0.12.10  v0.12.11  v0.12.12  v0.12.13  v0.12.14  v0.12.15
v0.12.16  v0.12.17  v0.12.18  

v4.0.0    v4.1.0    v4.1.1    v4.1.2    v4.2.0    v4.2.1    v4.2.2    v4.2.3
v4.2.4    v4.2.5    v4.2.6    v4.3.0    v4.3.1    v4.3.2    v4.4.0    v4.4.1
v4.4.2    v4.4.3    v4.4.4    v4.4.5    v4.4.6    v4.4.7    v4.5.0    v4.6.0
v4.6.1    v4.6.2    v4.7.0    v4.7.1    v4.7.2    v4.7.3    v4.8.0    v4.8.1
v4.8.2    v4.8.3    v4.8.4    v4.8.5    v4.8.6    v4.8.7    v4.9.0    v4.9.1


v5.0.0    v5.1.0    v5.1.1    v5.2.0    v5.3.0    v5.4.0    v5.4.1    v5.5.0
v5.6.0    v5.7.0    v5.7.1    v5.8.0    v5.9.0    v5.9.1    v5.10.0   v5.10.1
v5.11.0   v5.11.1   v5.12.0   

v6.0.0    v6.1.0    v6.2.0    v6.2.1    v6.2.2    v6.3.0    v6.3.1    v6.4.0
v6.5.0    v6.6.0    v6.7.0    v6.8.0    v6.8.1    v6.9.0    v6.9.1    v6.9.2
v6.9.3    v6.9.4    v6.9.5    v6.10.0   v6.10.1   v6.10.2   v6.10.3   v6.11.0
v6.11.1   v6.11.2   v6.11.3   v6.11.4   v6.11.5   v6.12.0   v6.12.1   v6.12.2
v6.12.3   v6.13.0   v6.13.1   v6.14.0   v6.14.1   v6.14.2   v6.14.3   v6.14.4
v6.15.0   v6.15.1   v6.16.0   v6.17.0   v6.17.1   

v7.0.0    v7.1.0    v7.2.0    v7.2.1    v7.3.0    v7.4.0    v7.5.0    v7.6.0
v7.7.0    v7.7.1    v7.7.2    v7.7.3    v7.7.4    v7.8.0    v7.9.0    v7.10.0
v7.10.1   

v8.0.0    v8.1.0    v8.1.1    v8.1.2    v8.1.3    v8.1.4    v8.2.0    v8.2.1
v8.3.0    v8.4.0    v8.5.0    v8.6.0    v8.7.0    v8.8.0    v8.8.1    v8.9.0
v8.9.1    v8.9.2    v8.9.3    v8.9.4    v8.10.0   v8.11.0   v8.11.1   v8.11.2
v8.11.3   v8.11.4   v8.12.0   v8.13.0   v8.14.0   v8.14.1   v8.15.0   v8.15.1
v8.16.0   v8.16.1   v8.16.2   v8.17.0   

v9.0.0    v9.1.0    v9.2.0    v9.2.1    v9.3.0    v9.4.0    v9.5.0    v9.6.0
v9.6.1    v9.7.0    v9.7.1    v9.8.0    v9.9.0    v9.10.0   v9.10.1   v9.11.0
v9.11.1   v9.11.2   

v10.0.0   v10.1.0   v10.2.0   v10.2.1   v10.3.0   v10.4.0   v10.4.1   v10.5.0
v10.6.0   v10.7.0   v10.8.0   v10.9.0   v10.10.0  v10.11.0  v10.12.0  v10.13.0
v10.14.0  v10.14.1  v10.14.2  v10.15.0  v10.15.1  v10.15.2  v10.15.3  v10.16.0
v10.16.1  v10.16.2  v10.16.3  v10.17.0  v10.18.0  v10.18.1  v10.19.0  v10.20.0
v10.20.1  v10.21.0  v10.22.0  v10.22.1  v10.23.0  v10.23.1  v10.23.2  v10.23.3
v10.24.0  v10.24.1  

v11.0.0   v11.1.0   v11.2.0   v11.3.0   v11.4.0   v11.5.0   v11.6.0   v11.7.0
v11.8.0   v11.9.0   v11.10.0  v11.10.1  v11.11.0  v11.12.0  v11.13.0  v11.14.0
v11.15.0  

v12.0.0   v12.1.0   v12.2.0   v12.3.0   v12.3.1   v12.4.0   v12.5.0   v12.6.0
v12.7.0   v12.8.0   v12.8.1   v12.9.0   v12.9.1   v12.10.0  v12.11.0  v12.11.1
v12.12.0  v12.13.0  v12.13.1  v12.14.0  v12.14.1  v12.15.0  v12.16.0  v12.16.1
v12.16.2  v12.16.3  v12.17.0  v12.18.0  v12.18.1  v12.18.2  v12.18.3  v12.18.4
v12.19.0  v12.19.1  v12.20.0  v12.20.1  v12.20.2  v12.21.0  v12.22.0  v12.22.1
v12.22.2  v12.22.3  v12.22.4  v12.22.5  v12.22.6  v12.22.7  v12.22.8  v12.22.9
v12.22.10 v12.22.11 v12.22.12 

v13.0.0   v13.0.1   v13.1.0   v13.2.0   v13.3.0   v13.4.0   v13.5.0   v13.6.0
v13.7.0   v13.8.0   v13.9.0   v13.10.0  v13.10.1  v13.11.0  v13.12.0  v13.13.0
v13.14.0  

v14.0.0   v14.1.0   v14.2.0   v14.3.0   v14.4.0   v14.5.0   v14.6.0   v14.7.0
v14.8.0   v14.9.0   v14.10.0  v14.10.1  v14.11.0  v14.12.0  v14.13.0  v14.13.1
v14.14.0  v14.15.0  v14.15.1  v14.15.2  v14.15.3  v14.15.4  v14.15.5  v14.16.0
v14.16.1  v14.17.0  v14.17.1  v14.17.2  v14.17.3  v14.17.4  v14.17.5  v14.17.6
v14.18.0  v14.18.1  v14.18.2  v14.18.3  v14.19.0  v14.19.1  v14.19.2  v14.19.3
v14.20.0  v14.20.1  v14.21.0  v14.21.1  

v15.0.0   v15.0.1   v15.1.0   v15.2.0   v15.2.1   v15.3.0   v15.4.0   v15.5.0
v15.5.1   v15.6.0   v15.7.0   v15.8.0   v15.9.0   v15.10.0  v15.11.0  v15.12.0
v15.13.0  v15.14.0  

v16.0.0   v16.1.0   v16.2.0   v16.3.0   v16.4.0   v16.4.1   v16.4.2   v16.5.0
v16.6.0   v16.6.1   v16.6.2   v16.7.0   v16.8.0   v16.9.0   v16.9.1   v16.10.0
v16.11.0  v16.11.1  v16.12.0  v16.13.0  v16.13.1  v16.13.2  v16.14.0  v16.14.1
v16.14.2  v16.15.0  v16.15.1  v16.16.0  v16.17.0  v16.17.1  v16.18.0  v16.18.1


v17.0.0   v17.0.1   v17.1.0   v17.2.0   v17.3.0   v17.3.1   v17.4.0   v17.5.0
v17.6.0   v17.7.0   v17.7.1   v17.7.2   v17.8.0   v17.9.0   v17.9.1   

v18.0.0   v18.1.0   v18.2.0   v18.3.0   v18.4.0   v18.5.0   v18.6.0   v18.7.0
v18.8.0   v18.9.0   v18.9.1   v18.10.0  v18.11.0  v18.12.0  v18.12.1  

v19.0.0   v19.0.1   

io@v1.0.0 io@v1.0.1 io@v1.0.2 io@v1.0.3 io@v1.0.4 io@v1.1.0 io@v1.2.0 io@v1.3.0
io@v1.4.1 io@v1.4.2 io@v1.4.3 io@v1.5.0 io@v1.5.1 io@v1.6.0 io@v1.6.1 io@v1.6.2
io@v1.6.3 io@v1.6.4 io@v1.7.1 io@v1.8.1 io@v1.8.2 io@v1.8.3 io@v1.8.4 

io@v2.0.0 io@v2.0.1 io@v2.0.2 io@v2.1.0 io@v2.2.0 io@v2.2.1 io@v2.3.0 io@v2.3.1
io@v2.3.2 io@v2.3.3 io@v2.3.4 io@v2.4.0 io@v2.5.0 

io@v3.0.0 io@v3.1.0 io@v3.2.0 io@v3.3.0 io@v3.3.1 
moritahayato@moritasatsuhitonoMacBook-Air Ishii-kadan % nodebrew install 14.16.01 
v14.16.01 is not found

Can not fetch: https://nodejs.org/dist/v14.16.01/node-v14.16.01-darwin-arm64.tar.gz
moritahayato@moritasatsuhitonoMacBook-Air Ishii-kadan % nodebrew compile 14.16.01
v14.16.01 is not found

Can not fetch: https://nodejs.org/dist/v14.16.01/node-v14.16.01.tar.gz
Can not fetch: https://nodejs.org/dist/node-v14.16.01.tar.gz
moritahayato@moritasatsuhitonoMacBook-Air Ishii-kadan % nodebrew use 12.16.01
v12.16.01 is not installed
moritahayato@moritasatsuhitonoMacBook-Air Ishii-kadan %

**Comment by yukinouz** [comment]
```zsh
nodebrew compile 14.16.01
v14.16.01 is not found
```
というエラー文が出ています。 
`v14.16.01`ではなく、`v14.16.1`じゃないですか？

それでもM1 Mac的な問題でインストールができないのであれば、[こちら](https://kotsukotsu.work/tech/2021-11-13-node-js-m1-mac-%E3%81%A7-nodebrew-%E3%81%8B%E3%82%89-node-v-16-0-0-%E6%9C%AA%E6%BA%80%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%99%E3%82%8B/)の方法を試すか、`v16.16.0`で再度インストールをお試しください。手元の環境で動くことを確認しました。

自分でエラー文をちゃんと読んでいるのでしょうか？どこのサイトを参考にされたのかわかりませんが、コピペしてうまくいかなかったら、自分でエラー原因を調べることなく質問していませんか？

**Comment by asdm-git** [comment]
調べた上で質問していますが。

**Comment by asdm-git** [comment]
エラー文をコピペしたりその他の方法を探してみたりしているのですが他に何か良い方法はありますか？質問しなくて済む方法があるなら教えてほしいです。

**Comment by yukinouz** [comment]
自分でお調べになったかどうかを伺ったのは下記の理由からです。

- 質問の際にスクショのみを貼って（それも消されたようですが）何を試して、どこでエラーが出て、何を試したのか？等々の説明がないため。
  - [質問テンプレート](https://github.com/yukinouz/gulp-essentials/issues/4)にも記載している[プログラマーに嫌われない質問術！プログラミングスキルアップに繋がる最高の質問のための3ポイントを紹介](https://tokyofreelance.jp/question/)に書いてある内容を再度ご確認ください。
- エラー文が出ているのに、そのまま次の処理に突き進んでいて、エラーに気づいたのか不明だった。「先に進みません」とだけ書かれており、自己解決のために何を考えたのかがわからない。

>質問されるようなノートのクオリティなので

わからない部分があるところは私の至らないところなので謝罪します。が、読者によって理解度に差があることも事実であるため、こうして質問対応をしています。
（`v14.16.1`での動作保証と記載していますので、そちらのバージョンを使用してください。で本来回答としては満たしているはずです。）

上記をよくお読みになって、精度の高い質問をしていただけると、もう少し精度の高い回答が返せると思います。

下記の方法はお試しになったのでしょうか？

```zsh
nodebrew compile 14.16.01
v14.16.01 is not found
```
というエラー文が出ています。 
`v14.16.01`ではなく、`v14.16.1`じゃないですか？

それでもM1 Mac的な問題でインストールができないのであれば、[こちら](https://kotsukotsu.work/tech/2021-11-13-node-js-m1-mac-%E3%81%A7-nodebrew-%E3%81%8B%E3%82%89-node-v-16-0-0-%E6%9C%AA%E6%BA%80%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%99%E3%82%8B/)の方法を試すか、`v16.16.0`で再度インストールをお試しください。手元の環境で動くことを確認しました。
