### ISSUE TITLE
処理速度についてご教授いただきたい

### ISSUE THREAD

**Issue by seisuke-iwamoto** [yukinouz/gulp-essentials#36]
はじめまして！
コーダーとして活動をしております岩本と申します！
普段のせっちさんのブログ記事に何度か助けられておりまして、普段から有益な発信ありがとうございます！
下記質問詳細になりますのでお忙しいところ恐縮ですが、お手隙の際にご確認いただけますと幸いです！

1. 聞きたいことの一行まとめ
使用しているGulpとのせっちさんが配布されているGulpの速度に差がある原因を知りたい（特にSCSSのコンパイル）

2. 起きている問題
![スクリーンショット 2023-02-09 18 20 32](https://user-images.githubusercontent.com/72451117/217771513-6f161eaf-2a44-4282-8aa8-4bdec039759e.jpg)

3. ソースコード（関連するソースコード/全ソースコード）
自身が使用しているgulpfile.jsになります。（コメントアウトや読みづらいコードですみません...）
また、下記スクショはのせっちさんのgulpfile.jsのSCSSのコンパイルの部分を自身が使っているSCSSのフォルダ構成でも処理が動くように少し改良して使用した結果になります。（SCSSのフォルダ構成や中のコードの量も同じにして実験してます）
https://drive.google.com/file/d/1v165rva2LmFcL5mPUn6DSbF6Un2OawJ7/view?usp=sharing

4. 問題解決するために試したこと（コードもあれば追記）
色々ググってみてgulp-cashedを導入してみたり、共有させていただいたファイルの通りSCSSのコンパイル以外の処理をコメントアウトして実行しないで使ってみたりと試行錯誤しました。
 
5. 問題について自分なりに考えたこと（デバッグ結果/検索結果/自分なりの原因予想）
デバック結果
体感としてはあまり変わらずで、特に気になるのがSCSSのエラー発生時から修正した時のコンパイルがかなり遅い（10〜20s）
これが一回ならいいのですがタイピング中にエラー判定しちゃうのでちりつもでかなり開発時にイライラしてしまいます...笑

自分なりの原因予想
共有させていただいたgulpfile.jsの通り実施しているタスクはSCSSのコンパイルのみにも関わらず、のせっちさんが作成されたgulpfaile.jsに関しては自身のものよりもかなり機能が多いにも関わらず速度が速いという点で原因としては記述の仕方が悪いのかと考えておりますが、JavaScriptのスキルが乏しく自身で解析できずご質問させていただきました。

 当コンテンツを購入したnoteのアカウント
seisuke-iwamoto

 noteのどのあたりまでやったのか（章のタイトル、小見出しのタイトルなど）
詳細を読んだところ読んでいないところがありますが全体的に拝見させていただきました。

**Comment by yukinouz** [comment]
seisuke-iwamotoさん

ご質問ありがとうございます。
僕のgulpと自分のgulpを比較して、sassのコンパイル速度に差があるのはなぜだろう...？というご質問でよろしいですか？

すみません>< 僕のGulpの方が早いのであればそちらを使っていただければいいと思うのですが、あくまでご自身のGulpを使っていきたい、ということでしょうか？それとも単純に速度差の原因を知りたい、ということですか？
noteの内容に関する質問ではないし、使ったことのないパッケージもあります。正直「知らねーよ」という感じではありますが、わかる範囲でお答えしますね。
予想も入っているので検証した結果違った、というご質問等はご遠慮いただけると助かります。

ざっと見てみて、gulp3以前に必要だった古いパッケージや記述を使っている点は気になりました。
- gulp-sourcemapsは不要です。（コメントアウトしているようですが）
- broswersはgulpではなく、`.browserslists`か、`package.json`に記述します。
  - また、かなり古いバージョンまで網羅しているようですが、こんな古いバージョンまでカバーしなくていいと思います。([参考:そのベンダープレフィックス、いつまでつけてるの？](https://qiita.com/amamamaou/items/42197e443134478befaf) )

上記が直接の原因ではないかもしれませんが、一旦気になったのでコメントしました。
こういうのを検証する際は、何がボトルネックになっているのかを検証した方がいいので、まずsassをコンパイルするだけのシンプルな状態から、一つずつパッケージを足していって、何を増やしたときに秒数が増えるのか、という感じで一つ一つ検証していく方法をオススメします。

僕の早さを目指したいのならば、僕のgulpに、seisuke-iwamotoが使っているパッケージを一つずつ足していって検証する方法もいいかもしれません。

**Comment by seisuke-iwamoto** [comment]
yukinouzさん

早速のご回答ありがとうございます！
また、noteに関係のないご質問をしてしまい大変申し訳ありませんでした...

質問の意図としてはおっしゃる通りで単純に速度の差はなぜだろうになります！
記述の古さや余計な記述をしてしまっている可能性があるということですね...
なんとなく予想していた内容と合致するので納得できました！

のせっちさんが配布されているGulp＋webpackがかなり使いやすく早速開発に使わせていただいております！笑
webpackを学ぶ機会も中々なかったのでjsのモジュール化などモダンフロントの導入の学習をするとても良い機会になりました！

良心的な価格での提供とてもありがたかったです！
