### ISSUE TITLE
Pug導入しない場合の第５章Cache Bustingの記述内容の確認とPug導入有無について

### ISSUE THREAD

**Issue by maruiyo7** [yukinouz/gulp-essentials#37]
聞きたいことの一行まとめ：
第４章Pug導入しない場合の（index.htmlはルートディレクトリ）第５章Cache Bustingの記述内容の確認とPug導入有無について

起きている問題：
❶Pugの導入を迷っているため、第４章を飛ばして第５章を自分なりに考えて記述変更しキャッシュクリア実行→下記のように表示されのですが、独自にコードを変更したので不安で確認頂きたいのと、今後移行の章も同様の対応でいいのかアドバイス頂きたいです。  link rel="stylesheet" href="dist/css/style.css?ver=002689069c0f5ef7"
 　　<script src="./js/script.js?ver=002689069c0f5ef7"></script>　
❷note内でPug使用を勧められていますが、私はやはりpug記法に慣れるのが大変そうで躊躇しているのですが、実務では一般的にほぼ皆さん導入されているのでしょうか？周囲の状況など私見でいいので参考までに伺えると助かります。

ソースコード：
const { src, dest, watch, series, parallel }  = require('gulp');
const sass = require('gulp-sass')(require('sass'));
const plumber = require('gulp-plumber');
const notify = require('gulp-notify');
const postcss = require('gulp-postcss');
const autoprefixer = require('autoprefixer');
const cssdeclsort = require('css-declaration-sorter');
const gcmq = require('gulp-group-css-media-queries'); 
const mode = require('gulp-mode')();
const browserSync = require('browser-sync');
const crypto = require('crypto');
const hash = crypto.randomBytes(8).toString('hex');
  const replace = require('gulp-replace');

const compileSass = (done) => {
  // postcssを纏めて変数に代入
  const postcssPlugins = [
    autoprefixer({
      grid: "autoplace",
      cascade: false,
    }),
    cssdeclsort({ order: 'alphabetical' })
  ];
  src('./src/scss/**/*.scss', { sourcemaps: true })
    .pipe(
      plumber({ errorHandler: notify.onError('Error: <%= error.message %>') })
    )
    .pipe(sass({ outputStyle: 'expanded' }))
    .pipe(postcss(postcssPlugins)) 
    .pipe(mode.production(gcmq()))
    .pipe(dest('./dist/css', { sourcemaps: './sourcemaps' }));
  done();
 };

 const buildServer = (done) => {
      browserSync.init({
      port: 8080,
       // 静的サイト
      server: { baseDir: './' },
       // 動的サイト
       // files: ["./**/*.php"],
       // proxy: "http://localsite.local/",
      open: true,
      watchOptions: {
      debounceDelay: 1000,
      },
      });
      done();
  };
  
  const browserReload = done => {
        browserSync.reload();
        done();
    };
　const cacheBusting = done => {
        src('./**/**.html')　//ルートディレクトリーのindex.htmlや下層含め変更
        .pipe(replace(/\.(js|css)\?ver/g, '.$1?ver=' + hash))
        .pipe(dest('./'))　//吐き出し先をルートディレクトリーに変更
        done();
    };
  const watchFiles = () => {
    watch( './src/scss/**/*.scss', series(compileSass, browserReload))
  };
  
module.exports = {
  sass: compileSass,
  cache: cacheBusting,
  default: parallel(buildServer, watchFiles),
};

問題解決するために試したこと：
1️⃣下記Pug該当欄を削除↓
const compilePug = done => {
  src(['./src/pug/**/*.pug', '!' + './src/pug/**/_*.pug'])
    .pipe(plumber(({ errorHandler: notify.onError('Error: <%= error.message %>') })))
    .pipe(pug({
      pretty: true
    }))
    .pipe(dest('./dist'))
     .on("end", done);
};
2️⃣下記コードの変更↓
　const cacheBusting = done => {
        src('./**/**.html')　//ルートディレクトリーのindex.htmlや下層含め変更
        .pipe(replace(/\.(js|css)\?ver/g, '.$1?ver=' + hash))
        .pipe(dest('./'))　//吐き出し先をルートディレクトリーに変更
        done();
    };

問題について自分なりに考えたこと：
pug使用しなくてもsrcやdest先を変更すれば問題なく使用できると考えていますが、
今後６章以降を進めるのにPug導入しない場合と記述内容が変わってくると思ったので、今後進めるに当たりアドバイス等頂きたいと思いました。

当コンテンツを購入したnoteのアカウント：maruiyo

noteのどのあたりまでやったのか（章のタイトル、小見出しのタイトルなど）：
第５章まで（第４章は飛ばした）

**Comment by yukinouz** [comment]
maruiyoさん

ご質問ありがとうございます。
コードレビューは本来やっていないので、お答えできかねるのですが、変更点のみ見てみますね！

```javascript
// maruiyoさんがご質問で記載した変更部分の抜粋
const cacheBusting = done => {
src('.//.html')
.pipe(replace(/.(js|css)?ver/g, '.$1?ver=' + hash))
.pipe(dest('./'))
done();
};
```

`ルートディレクトリーのindex.htmlや下層含め変更`したいのであれば、こうじゃないですかね？

```diff
const cacheBusting = done => {
- src('.//.html')
+ src('./**/**.html')
.pipe(replace(/.(js|css)?ver/g, '.$1?ver=' + hash))
.pipe(dest('./'))
done();
};
```

>note内でPug使用を勧められていますが、私はやはりpug記法に慣れるのが大変そうで躊躇しているのですが、実務では一般的にほぼ皆さん導入されているのでしょうか？周囲の状況など私見でいいので参考までに伺えると助かります

慣れたら全員pugになるかというとそうではないと思うので使いたくなければ使わなくてOKですよ！

**Comment by maruiyo7** [comment]
のせっち　様

本来レビューしていないのに、見ていただけて安心しました。ありがとうございます。
（下層含めコードに変更した際に、問い合わせフォームのコードを上書き忘れていました。同じ認識です）
Pugについても、しばらく様子を見てみることにします。ご返答ありがとうございました！！

maruiyo
