### ISSUE TITLE
Sassのコンパイルについて

### ISSUE THREAD

**Issue by manato0305** [yukinouz/gulp-essentials#7]
以下のテンプレートを使って質問をお願いします！

聞きたいことの一行まとめ
⇨gulpがインストールできない

起きている問題（起きている現象の詳細/エラーメッセージ/スクリーンショット）
⇨恐らくファイルがダウンロードできておらずSassがコンパイルされない

ソースコード（関連するソースコード/全ソースコード）
⇨添付します。

問題解決するために試したこと（コードもあれば追記）
⇨gulpのインストールについて調べてみて、似たような内容だと感じたので、とりあえず追記してみましたが、解決できませんでした。
https://www.it-swarm-ja.com/ja/npm/gulp%e3%82%b3%e3%83%9e%e3%83%b3%e3%83%89%e3%81%8c%e8%a6%8b%e3%81%a4%e3%81%8b%e3%82%8a%e3%81%be%e3%81%9b%e3%82%93/827658759/

https://teratail.com/questions/299918

問題について自分なりに考えたこと（デバッグ結果/検索結果/自分なりの原因予想）
⇨コンパイルの際に、ファイルが見当たらないと出ていたので、gulpかnode_moduelにsassのファイルのどちらかが欠けていると予想しました。

当コンテンツを購入したnoteのアカウント
⇨manato3588@gmail.com

noteのどのあたりまでやったのか（章のタイトル、小見出しのタイトルなど）
⇨2-4のSassをコンパイルし、dist/cssに反映される予定のところまでです。

GitHubやGistを使ってもらえると助かります！
使い方がわからない方はGoogleDriveとかでもOKです。

こちらがファイルになります。
[gulp-essentials.zip](https://github.com/yukinouz/gulp-essentials/files/6755754/gulp-essentials.zip)
こちらがターミナル表記になります。
`Last login: Sat Jul  3 00:02:14 on ttys000
ikedamanato@ikedamakotonoMacBook-Air ~ % /Users/ikedamanato/Desktop/gulp-essentials cd Desktop
zsh: permission denied: /Users/ikedamanato/Desktop/gulp-essentials
ikedamanato@ikedamakotonoMacBook-Air ~ % npm init -y
Wrote to /Users/ikedamanato/package.json:

{
  "name": "ikedamanato",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "fibers": "^5.0.0",
    "gulp-sass": "^5.0.0",
    "gulp": "^4.0.2",
    "node-sass": "^6.0.1",
    "sass": "^1.35.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

ikedamanato@ikedamakotonoMacBook-Air ~ % npm i -D gulp
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm notice save gulp is being moved from dependencies to devDependencies
npm WARN ikedamanato@1.0.0 No description
npm WARN ikedamanato@1.0.0 No repository field.

+ gulp@4.0.2
updated 1 package and audited 517 packages in 13.132s

15 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
ikedamanato@ikedamakotonoMacBook-Air ~ % git clone -b initial https:
Cloning into 'https'...
ssh: Could not resolve hostname https: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ikedamanato@ikedamakotonoMacBook-Air ~ % git clone -b install-gulp-sass https:
Cloning into 'https'...
ssh: Could not resolve hostname https: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ikedamanato@ikedamakotonoMacBook-Air ~ % npm install
npm WARN ikedamanato@1.0.0 No description
npm WARN ikedamanato@1.0.0 No repository field.

audited 517 packages in 2.453s

19 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
ikedamanato@ikedamakotonoMacBook-Air ~ % 
`

『当該コンテンツを購入したnoteのアカウント』について、
note のアカウントを明記してください。購入者のみが対応できるようにするためです。
manato3588@gmail.com

ご対応よろしくお願いいたします。

**Comment by manato0305** [comment]
すみません！自己解決できました。

gulp-sass 5 does not have a default Sass compiler; please set one yourself. Both the `sass` and `node-sass` packages are permitted. For example, in your gulpfile:

というエラーが出ており、

const sass = require('gulp-sass')
↓
var sass = require('gulp-sass')(require('sass'));

をしたらコンパイルできました！！

**Comment by yukinouz** [comment]
お疲れ様です！
エラー自己解決でき、よかったです。
エラーメッセージを自分で読んで解決でき、素晴らしいですm(_ _)m

closeします。

**Comment by yukinouz** [comment]
gulp-sassが最近ver5にアップデートされ、manato0305 さんが記載の通り記述を変更する必要があるようですね！
https://www.npmjs.com/package/gulp-sass

貴重な情報ありがとうございます。
こちら、noteの方も情報をアップデートしたいと思います。

**Comment by manato0305** [comment]
アップデートの兼ね合いだったんですね！

貴重な体験になりました！
引き続きよろしくお願いいたします。

**Comment by manato0305** [comment]
お疲れ様です。
今一通り設定が終わり、感動に浸っているところです。
このような便利な環境構築はまず自分ではできないですし、調べても答え合わせや擦り合わせができない中で一人でやるのはかなりきついので、本当に助かりました。
ありがとうございます。

一点気づいた箇所があるので共有させて頂きます。
5-1. パッケージのインストールのGitHubで追記されている部分で、定義が二つ追加されている箇所の上の
const crypto = require('crypto');
の定義が恐らくこのタイミングで追加されたわけではないかもしれませんが、見ながら進めている身としては、ここもこのタイミングで追加しないとエラーになりました。

僕はたまたま目を凝らして見ていたので、なんとか気付けましたが、他が全部追記すれば完璧に動くようになっている関係でここだけ追記しても動かない事態が起きてしまうかもしれないと思いお伝えさせて頂きました。

もし敢えてでしたら、大きなお世話になると思うのであらかじめ謝っておきます。大きなお世話でしたら申し訳ございません。

他の箇所がズレがなく完璧でここだけそうではなかったので、個人的にはすごく引っかかってしまいました。汗

とはいえ、Googleで検索して出る情報より遥かに具体的で解説も丁寧だったので僕は上記以降躓きませんでした。

改めて感謝お伝えさせて頂きます。
ありがとうございました。

**Comment by yukinouz** [comment]
まずは、設定完了おめでとうございます！
僕のnoteが少しでもお役に立てれば幸いです^^

ご指摘の件ありがとうございます！
これは完全に僕のミスですね>< ご指摘ありがとうございますTT
同じところで詰まる方が出る可能性があり、どんなに細かな点でもこういったご指摘大変感謝ですm(_ _)m

今Gistの方は更新しましたm(_ _)m

**Comment by manato0305** [comment]
それでしたら良かったです🙇‍♂️

そこだけが気になってしまったので、お伝えさせていただきました。

今後の使い方についてなのですが、新しいフォルダでvscodeを開いて、ターミナル→新しいターミナルを選択すると設定された環境になるという認識で合ってるのでしょうか？

**Comment by yukinouz** [comment]
>今後の使い方についてなのですが、新しいフォルダでvscodeを開いて、ターミナル→新しいターミナルを選択すると設定された環境になるという認識で合ってるのでしょうか？

んー、よくわからないですが、多分違いますw

今回作成した、
- package.json
- package-lock.json
- gulpfile.js

を新規作成したプロジェクトにコピペして、ターミナルで

```bash
npm install
```

することで構築したGulp環境を再現することが可能です！

（.browserslistrcやsrcフォルダ、distフォルダなども一緒に持っていくとディレクトリ構成やautoplefixerの設定も含めて完全再現できます。）

この辺の解説も必要でしたね！
これもその内追記したいと思いますm(_ _)m

**Comment by manato0305** [comment]
なるほどです笑
全然違いました笑

これで使い方も分かったので、助かりました！
ありがとうございました🙇‍♂️
